
#
# Site settings
#
author: Vo Quoc Duy
url: http://microbus.asia
title: Microbus
email: duyvq.vn@gmail.com
tagline: Do Less, Know More
baseurl: ""
description: Microbus is a startup company with a mission to provide smart technology solutions and help engineers build their product easily.

collections:
  products:
    output: true

#
# Social Media
#
social:
  - title: facebook
    url: https://facebook.com/mircobus
  - title: github
    url: https://github.com/MicrobusAsia
  - title: rss
    url: /feed.xml

#
# Google Analytics
# 
google_analytics_tracking_id: 


#
# Disqus Comments
#
disqus_short_name: microbus-asia
disqus_show_comment_count: true


#
# Jekyll Settings
#
markdown: kramdown
permalink: pretty


#
# Jekyll Plugins (Compatible with Github Pages)
#
gems:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap

 

theme: jekyll-theme-cayman